### ISSUE TITLE
Ad margins need flexibility

### ISSUE THREAD

**Issue by VSEphpbb** [phpbb-extensions/ad-management#6]
The 10px margins added to our ads need to be more flexible.

We should separate the margin into a separate class.

The reason is so, for example individual template locations, or other extensions extending our locations, can choose if they want the margins or not.

e.g.: 
```html
<div class="ad-center ad-margin">{{ AD_BEFORE_HEADER }}</div>
```
```css
.ad-center {
	display: flex;
	justify-content: center;
}

.ad-margin {
	margin: 10px 0;
}
```
